package ca.uwo.csd.cs2212.team12;

//NOT IMPLEMENTED IN STAGE TWO BUT WILL MOST LIKELY BE USED AS A FUTURE REFERENCE
//EMPTY CLASS USED TO HELP ILLUSTRATE
//HOW INFORMATION MIGHT MOVE THROUGH THE PROGRAMME
public class JSON {

}
